rm ./04-include-feature-module/$1
rm ./05-create-footer-component/$1
rm ./06-create-playground-service/$1
rm ./07-add-ajax-to-playground-service/$1
rm ./08-create-location-service/$1
rm ./09-include-the-map/$1
rm ./10-add-some-pipes/$1
rm ./11-add-some-routes/$1
rm ./12-add-filter-to-sidebar/$1

rm ../solutions/03-create-first-component/$1
rm ../solutions/04-include-feature-module/$1
rm ../solutions/05-create-footer-component/$1
rm ../solutions/06-create-playground-service/$1
rm ../solutions/07-add-ajax-to-playground-service/$1
rm ../solutions/08-create-location-service/$1
rm ../solutions/09-include-the-map/$1
rm ../solutions/10-add-some-pipes/$1
rm ../solutions/11-add-some-routes/$1
rm ../solutions/12-add-filter-to-sidebar/$1
